# Generated by Django 3.0.8 on 2020-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_filesup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filesUp',
            field=models.FileField(upload_to='./templates/upload/'),
        ),
    ]
