# Generated by Django 3.0.8 on 2020-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200727_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filesUp',
            field=models.FileField(upload_to='blog/templates/upload/'),
        ),
    ]
